### ISSUE TITLE
Translate DLang Tour title into Russian

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/russian#29]
FYI: You can change the title of the [DLang Tour](http://tour.dlang.org/tour/ru) to Russian at the main [`index.yml`](https://github.com/dlang-tour/russian/blob/master/index.yml) file if you want to. The menu titles can be changed in their respective `index.yml` of the according folder.

**Comment by radcapricorn** [comment]
@wilzbach This looks to be fixed by Ilya (8a6b561bdf91e6bf12c41bde9137c8312fa48187)
